CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255)                            NOT NULL,
    document   VARCHAR(14)                             NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    user_type  VARCHAR(255)                            NOT NULL,
    wallet_id  BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_document UNIQUE (document);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE TABLE wallet
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    balance    DECIMAL(19, 4)                          NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_wallet PRIMARY KEY (id)
);

ALTER TABLE wallet
    ADD CONSTRAINT chk_wallet_balance_positive CHECK (balance > 0);

CREATE TABLE transactions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version        BIGINT,
    payer_id       BIGINT,
    payee_id       BIGINT,
    amount         DECIMAL(19, 2)                          NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    failure_reason TEXT,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);